Solicitus de goenitz3 para la legion
macrey-services/legion-del-bien pull request #1
Opened 2021-07-29 23:44 UTC by goenitz3

### Modificaciones
Borré al Scarecrow

### Adiciones
 Cree una carpe y dentro d esta un archivo de solicitud de colaborador.

2021-07-29 23:59 UTC, macrey-services requested changes
Por favor no borren al Scarecrow 👍

2021-07-29 23:59 UTC, macrey-services commented on miembros.md
> -23. Scarecrow
No quiero que borren al Scarecrow 👎

2021-07-30 00:12 UTC, goenitz3 commented on miembros.md
> -23. Scarecrow
Esta bien no lo voy a borrar.

2021-07-30 00:26 UTC, macrey-services approved these changes
Muy bien colaboración aprovada

2021-07-30 00:33 UTC, merged